apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dmwf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-dmwf@sha256:85046988d836e825185911769ac3a4d659c38f2db80f2b2ae0f21071629f67e1
        name: my-nodejs
        resources: {}
status: {}
